Updated build scripts.

diff --git a/make-deb b/make-deb
--- a/make-deb
+++ b/make-deb
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
-# Debian Packaging Scripts
-# Copyright (C) 2002-2020 by Thomas Dreibholz
+# Debian/Ubuntu Packaging Scripts
+# Copyright (C) 2002-2021 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -35,7 +35,7 @@ set -e
 # Set current Debian debhelper version here
 # for building unstable/testing/stable packages
 # (See https://packages.qa.debian.org/d/debhelper.html for latest version!)
-DEBHELPER_LATEST_VERSION="12"
+DEBHELPER_LATEST_VERSION="13"
 
 
 # ====== Obtain package and version information =============================
@@ -165,10 +165,10 @@ for DISTRIBUTION in ${DISTRIBUTIONS} ; do
              <debian/changelog | ../filter-empty-entries "$DEBIAN_LAST_ENTRY" >debian/changelog.new
       else
          # Ubuntu PPA
-         # Naming example: 2.7.7-0ubuntu1~natty1~ppa0
+         # Naming example: 2.7.7-1ubuntu~focal1
          # Ubuntu: Also remove Debian Bug IDs.
          sed -e "s/${PACKAGE_DISTRIBUTION};/${DISTRIBUTION};/1" \
-             -e "s/${PACKAGE_VERSION}/${PACKAGE_VERSION}~${DISTRIBUTION}1~ppa0/1" \
+             -e "s/${PACKAGE_VERSION}/${OUTPUT_VERSION}~${DISTRIBUTION}1/1" \
              -e "/(Closes: #/D" \
              <debian/changelog | ../filter-empty-entries "$UBUNTU_LAST_ENTRY" >debian/changelog.new
 
@@ -253,10 +253,14 @@ for DISTRIBUTION in ${DISTRIBUTIONS} ; do
    fi
    if [ ${SKIP_PACKAGE_SIGNING} -eq 1 -o "${OVERRIDE_SKIP_PACKAGE_SIGNING}" == "1" ] ; then
       # Build source package without signature:
-      debuild ${opt} -us -uc -S "-k${MAINTAINER}" -i || exit 1
+      debuild ${opt} -us -uc -S -i || exit 1
    else
       # Build source package including signature:
-      debuild ${opt} -sa -S "-k${MAINTAINER}" -i || exit 1
+      if [ "${MAINTAINER_KEY}" == "" ] ; then
+         echo >&2 "ERROR: MAINTAINER_KEY is not set!"
+         exit 1
+      fi
+      debuild ${opt} -sa -S "-k${MAINTAINER_KEY}" -i || exit 1
    fi
 
    # Important: In /etc/pbuilderrc, set COMPONENTS="main universe"!
@@ -276,7 +280,7 @@ for DISTRIBUTION in ${DISTRIBUTIONS} ; do
       fi
       dscFile=`ls ${PACKAGE}_${version}.dsc | tail -n1`
    else
-      dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9].dsc | tail -n1`
+      dscFile=`ls ${PACKAGE}_${OUTPUT_VERSION}~${DISTRIBUTION}[0-9].dsc | tail -n1`
    fi
    if [ ! -e "${dscFile}" ] ; then
       echo -e "\x1b[34mERROR: ${dscFile} has not been generated successfully -> Aborting!\x1b[0m"
@@ -307,7 +311,7 @@ for DISTRIBUTION in ${DISTRIBUTIONS} ; do
       changesFile=`ls ${PACKAGE}_${version}_source.changes | tail -n1`
    else
       ppa="ppa"
-      changesFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9]_source.changes | tail -n1`
+      changesFile=`ls ${PACKAGE}_${OUTPUT_VERSION}~${DISTRIBUTION}[0-9]_source.changes | tail -n1`
    fi
    echo -e "\x1b[34m   dput ${ppa} $changesFile\x1b[0m"
 done
@@ -334,8 +338,8 @@ for DISTRIBUTION in ${DISTRIBUTIONS} ; do
       changesFilesPattern="${PACKAGE}_${version}_*.changes"
       dscFile=`ls ${PACKAGE}_${version}.dsc | tail -n1`
    else
-      changesFilesPattern="${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9]_*.changes"
-      dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9].dsc | tail -n1`
+      changesFilesPattern="${PACKAGE}_${OUTPUT_VERSION}~${DISTRIBUTION}[0-9]_*.changes"
+      dscFile=`ls ${PACKAGE}_${OUTPUT_VERSION}~${DISTRIBUTION}[0-9].dsc | tail -n1`
    fi
    profile="ubuntu"
    if [ "${DISTRIBUTION}" == "unstable" -o \
